### ISSUE TITLE
Broken Link on Training hotsite

### ISSUE THREAD

**Issue by luizcarlosfaria** [wso2/WSO2-Training#1]
Today Luiza Camargo tell me about training website, during first steps i found broken links to github "WSO2-Training" repository.

Website page: http://wso2.com/training/api-manager-developer-fundamentals
Link Subject: **Download Presentation**
Broken Target: [link](https://github.com/wso2/WSO2-Training/releases/download/APIM2.0.0DF/APIM200DF-Presentations-PDF.zip)
Correct Target: [pptx version](
https://github.com/wso2/WSO2-Training/releases/download/APIM2.0.0DF/APIM200DF-Presentations-PPTX.zip) or [pdf version](https://github.com/wso2/WSO2-Training/releases/download/APIM2.0.0DF/APIM200_DF_Presentations_PDF.zip)

**Comment by appellj** [comment]
This has been fixed. Thank you for reporting the issue!
